### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by subhomoy-roy-choudhury** [subhomoy-roy-choudhury/Hack_IP#5]
- [x] Update Readme.md
- [x] Add website docs

Reference Links:- 
- Readme Generator:- https://nxt-readme.vercel.app/editor
- Documentation sie :- https://github.com/docsifyjs/docsify

**Comment by saisreesatyassss** [comment]
i would like to work on it give me further infomation and what to do

**Comment by subhomoy-roy-choudhury** [comment]
Yaa sure
